#!/bin/bash

PATH="$(pwd)/target/release:$PATH"

entries_sizes=(2 4 8)
algorithms=(second-chance lru counter)

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit 1
fi

file_name=$1

for entries in "${entries_sizes[@]}"
do
  printf "============= %d entries =============\n\n" "$entries"
  for algorithm in "${algorithms[@]}"
  do
    echo "$algorithm:"
    pal_rs translate $file_name --pal-table-entries $entries --algorithm $algorithm
    echo
  done
done
